### ISSUE TITLE
Xcos-HDL

### ISSUE THREAD

**Issue by manasdas17** [amartens/ratel#1]
This is Manas from IIT-Bombay,India.Your work of Xcos to HDL is a great piece of work.Plz let me know when are you planning to release a complete version of it.Could i have your mail-id.Mine is manasdas17@gmail.com.I want to contribute to the developement.

Regards,
Manas

**Comment by amartens** [comment]
Hi Manas. I am doing some work on this but it will be some time before I can release anything. I am not sure when. When I have something more final I will welcome help, but at the moment things are changing a lot as I learn new things so it will be hard to work with someone. Thanks for the offer, I will definitely welcome it soon

**Comment by phobik** [comment]
any updates?
